version: '3.8'

services:
  frontend:
    build: ../
    container_name: frontend
    ports:
      -  "${PORT:-8080}:${PORT:-8080}"
    volumes:
      - ../:/usr/src/app
    external_links:
      - api_backend # Change this to your backend if it's called something different
    environment:
      - PORT=${PORT}