version: '3.8'

services:
  frontend:
    build: ../
    container_name: frontend
    ports:
      - "${PORT}:${PORT}"  # Map the dynamic PORT variable to container port 8081
    volumes:
      - ../:/usr/src/app
    external_links:
      - api_backend # Change this to your backend if it's called something different
